/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Main.BD;
import java.awt.Color;

/**
 *
 * @author Carlos Moyano
 */
public class Productos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Productos.class.getName());

    /**
     * Creates new form Productos
     */
    public Productos() {
        initComponents();
        
        cargarProductos();  
        
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
        });
    }
    
    private void cargarProductos() {
        DefaultTableModel modelo = (DefaultTableModel) tblProductos.getModel();
        modelo.setRowCount(0); // Limpiar tabla

        String sql = "SELECT p.prod_id, p.prod_nombre, p.prod_precio, p.prod_stock, " +
             "(p.prod_alto || 'x' || p.prod_ancho || 'x' || p.prod_profundidad) AS dimensiones, " +
             "m.mat_nombre, c.cat_nombre, p.prod_estado, p.prod_iva, " +
             "(SELECT COUNT(*) FROM MUE_DETALLES_FACTURAS df WHERE df.prod_id = p.prod_id) AS en_factura " +
             "FROM MUE_PRODUCTOS p " +
             "JOIN MUE_MATERIALES_PRODUCTOS m ON p.mat_id = m.mat_id " +
             "JOIN MUE_CATEGORIAS c ON p.cat_id = c.cat_id";

        try (Connection con = BD.conectar();
             Statement stmt = con.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {

            while (rs.next()) {
                String estado;
                if (rs.getInt("en_factura") > 0) {
                    estado = "I";
                } else {
                    estado = rs.getString("prod_estado").equals("A") ? "A" : "I";
                }

                Object[] fila = {
                    rs.getInt("prod_id"),
                    rs.getString("prod_nombre"),
                    rs.getDouble("prod_precio"),
                    rs.getInt("prod_stock"),
                    rs.getString("mat_nombre"),
                    rs.getString("cat_nombre"),
                    rs.getString("dimensiones"),
                    estado,
                    rs.getString("prod_iva")
                };
                modelo.addRow(fila);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al cargar productos: " + e.getMessage());
        }
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitBtn1 = new javax.swing.JPanel();
        bg = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        lblNombre1 = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();
        lblIVA = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblAncho = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        lblAlto1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        txtProfundidad = new javax.swing.JTextField();
        txtAncho = new javax.swing.JTextField();
        txtAlto = new javax.swing.JTextField();
        btnAgregarProductos = new javax.swing.JButton();
        lblCrearProd1 = new javax.swing.JLabel();
        btnBuscarProd = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        cmbIVA = new javax.swing.JComboBox<>();
        btnActualizarProd = new javax.swing.JButton();
        lblNombre2 = new javax.swing.JLabel();
        cmbCategoria = new javax.swing.JComboBox<>();
        lblMaterial1 = new javax.swing.JLabel();
        cmbMaterial = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        lblListadoProd = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();

        exitBtn1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout exitBtn1Layout = new javax.swing.GroupLayout(exitBtn1);
        exitBtn1.setLayout(exitBtn1Layout);
        exitBtn1Layout.setHorizontalGroup(
            exitBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        exitBtn1Layout.setVerticalGroup(
            exitBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));

        exitTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("<");
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 788, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 40));

        title.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        title.setText("Productos");
        bg.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 710, 20));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblNombre1.setText("Nombre:");
        jPanel1.add(lblNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        lblStock.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblStock.setText("Stock:");
        jPanel1.add(lblStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        lblIVA.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblIVA.setText("IVA:");
        jPanel1.add(lblIVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        lblEstado.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblEstado.setText("Profundidad (cm):");
        jPanel1.add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, -1));

        lblAncho.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblAncho.setText("Ancho (cm):");
        jPanel1.add(lblAncho, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        lblCategoria.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblCategoria.setText("Categoria:");
        jPanel1.add(lblCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));

        lblAlto1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblAlto1.setText("Alto (cm):");
        jPanel1.add(lblAlto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 230, -1));

        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 100, -1));

        txtStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockActionPerformed(evt);
            }
        });
        jPanel1.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 230, -1));
        jPanel1.add(txtProfundidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 190, -1));
        jPanel1.add(txtAncho, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 190, -1));
        jPanel1.add(txtAlto, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 190, -1));

        btnAgregarProductos.setBackground(new java.awt.Color(255, 153, 0));
        btnAgregarProductos.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnAgregarProductos.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarProductos.setText("AGREGAR");
        btnAgregarProductos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAgregarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductosActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 100, 30));

        lblCrearProd1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblCrearProd1.setText("Crear Producto");
        jPanel1.add(lblCrearProd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        btnBuscarProd.setBackground(new java.awt.Color(255, 153, 0));
        btnBuscarProd.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnBuscarProd.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarProd.setText("BUSCAR");
        btnBuscarProd.setBorder(null);
        btnBuscarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProdActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 100, 30));

        btnEliminar.setBackground(new java.awt.Color(255, 153, 0));
        btnEliminar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setBorder(null);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 100, 30));

        cmbIVA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "1", "0" }));
        jPanel1.add(cmbIVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 80, -1));

        btnActualizarProd.setBackground(new java.awt.Color(255, 153, 0));
        btnActualizarProd.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnActualizarProd.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarProd.setText("ACTUALIZAR");
        btnActualizarProd.setBorder(null);
        btnActualizarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarProdActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 100, 30));

        lblNombre2.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblNombre2.setText("Precio:");
        jPanel1.add(lblNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Sala", "Comedor", "Cocina", "Dormitorio", "Exterior" }));
        cmbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoriaActionPerformed(evt);
            }
        });
        jPanel1.add(cmbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 230, -1));

        lblMaterial1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblMaterial1.setText("Material:");
        jPanel1.add(lblMaterial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        cmbMaterial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Madera", "Metal", "Plastico" }));
        jPanel1.add(cmbMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 230, -1));

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 710, 230));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblListadoProd.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblListadoProd.setText("Listado de Productos");
        jPanel2.add(lblListadoProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 641, 660, 210));

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Precio ", "Stock", "Material", "Categoria", "Dimensiones", "Estado", "IVA"
            }
        ));
        jScrollPane2.setViewportView(tblProductos);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 690, 170));

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 710, 250));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged

    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed

    }//GEN-LAST:event_headerMousePressed

    private void btnAgregarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductosActionPerformed
        try (Connection con = BD.conectar()) {
            String sql = "INSERT INTO MUE_PRODUCTOS (prod_id, prod_nombre, prod_precio, prod_stock, " +
                        "prod_IVA, prod_estado, prod_alto, prod_ancho, prod_profundidad, mat_id, cat_id) " +
                        "VALUES (prod_id_seq.NEXTVAL, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";


            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, txtNombre.getText());
            ps.setDouble(2, Double.parseDouble(txtPrecio.getText()));
            ps.setInt(3, Integer.parseInt(txtStock.getText()));
            ps.setString(4, cmbIVA.getSelectedItem().toString()); // 'S' o 'N'
            ps.setString(5, "A"); // Estado por defecto
            ps.setInt(6, Integer.parseInt(txtAlto.getText()));
            ps.setInt(7, Integer.parseInt(txtAncho.getText()));
            ps.setInt(8, Integer.parseInt(txtProfundidad.getText()));
            ps.setInt(9, cmbMaterial.getSelectedIndex());  // Asume que ID comienza en 1
            ps.setInt(10, cmbCategoria.getSelectedIndex());

            int filas = ps.executeUpdate();

            if (filas > 0) {
                JOptionPane.showMessageDialog(null, "Producto registrado correctamente.");
                cargarProductos();
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo registrar el producto.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnAgregarProductosActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockActionPerformed

    private void btnBuscarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProdActionPerformed
        String nombre = txtNombre.getText().trim();

        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese un nombre de producto.");
            return;
        }

        String sql = "SELECT * FROM MUE_PRODUCTOS WHERE LOWER(prod_nombre) = LOWER(?)";

        try (Connection con = BD.conectar();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setString(1, nombre);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                txtPrecio.setText(rs.getString("prod_precio"));
                txtStock.setText(rs.getString("prod_stock"));
                cmbIVA.setSelectedItem(rs.getString("prod_IVA"));
                txtAlto.setText(rs.getString("prod_alto"));
                txtAncho.setText(rs.getString("prod_ancho"));
                txtProfundidad.setText(rs.getString("prod_profundidad"));

                cmbMaterial.setSelectedIndex(rs.getInt("mat_id") - 1); // si mat_id empieza desde 1
                cmbCategoria.setSelectedIndex(rs.getInt("cat_id") - 1);

                JOptionPane.showMessageDialog(null, "Producto encontrado. Ahora puedes actualizar.");
            } else {
                JOptionPane.showMessageDialog(null, "Producto no encontrado.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al buscar producto: " + e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarProdActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String nombre = txtNombre.getText().trim();

        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese el nombre del producto a eliminar.");
            return;
        }

        String sqlCheck = "SELECT COUNT(*) FROM MUE_DETALLES_FACTURAS df " +
                          "JOIN MUE_PRODUCTOS p ON p.prod_id = df.prod_id " +
                          "WHERE LOWER(p.prod_nombre) = LOWER(?)";

        String sqlDelete = "DELETE FROM MUE_PRODUCTOS WHERE LOWER(prod_nombre) = LOWER(?)";
        String sqlDesactivar = "UPDATE MUE_PRODUCTOS SET prod_estado = 'I' WHERE LOWER(prod_nombre) = LOWER(?)";

        try (Connection con = BD.conectar();
             PreparedStatement psCheck = con.prepareStatement(sqlCheck)) {

            psCheck.setString(1, nombre);
            ResultSet rs = psCheck.executeQuery();

            if (rs.next() && rs.getInt(1) > 0) {
                // Asociado a factura
                int op = JOptionPane.showConfirmDialog(null, "El producto está en una factura. ¿Deseas desactivarlo?", "Confirmar", JOptionPane.YES_NO_OPTION);
                if (op == JOptionPane.YES_OPTION) {
                    try (PreparedStatement ps = con.prepareStatement(sqlDesactivar)) {
                        ps.setString(1, nombre);
                        ps.executeUpdate();
                        JOptionPane.showMessageDialog(null, "Producto desactivado.");
                    }
                }
            } else {
                // No está en factura, eliminar
                int op = JOptionPane.showConfirmDialog(null, "¿Deseas eliminar el producto?", "Eliminar", JOptionPane.YES_NO_OPTION);
                if (op == JOptionPane.YES_OPTION) {
                    try (PreparedStatement ps = con.prepareStatement(sqlDelete)) {
                        ps.setString(1, nombre);
                        ps.executeUpdate();
                        JOptionPane.showMessageDialog(null, "Producto eliminado.");
                        txtNombre.setText("");
                        txtPrecio.setText("");
                        txtStock.setText("");
                        txtAlto.setText("");
                        txtAncho.setText("");
                        txtProfundidad.setText("");
                        cmbIVA.setSelectedIndex(0);
                        cmbMaterial.setSelectedIndex(0);
                        cmbCategoria.setSelectedIndex(0);
                    }
                }
            }

            cargarProductos();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al eliminar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarProdActionPerformed
        String nombre = txtNombre.getText().trim();

        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese el nombre del producto a actualizar.");
            return;
        }

        String sql = "UPDATE MUE_PRODUCTOS SET prod_precio = ?, prod_stock = ?, prod_IVA = ?, " +
                     "prod_alto = ?, prod_ancho = ?, prod_profundidad = ?, mat_id = ?, cat_id = ? " +
                     "WHERE LOWER(prod_nombre) = LOWER(?)";

        try (Connection con = BD.conectar();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setDouble(1, Double.parseDouble(txtPrecio.getText()));
            ps.setInt(2, Integer.parseInt(txtStock.getText()));
            ps.setString(3, cmbIVA.getSelectedItem().toString());
            ps.setInt(4, Integer.parseInt(txtAlto.getText()));
            ps.setInt(5, Integer.parseInt(txtAncho.getText()));
            ps.setInt(6, Integer.parseInt(txtProfundidad.getText()));
            ps.setInt(7, cmbMaterial.getSelectedIndex() + 1);
            ps.setInt(8, cmbCategoria.getSelectedIndex() + 1);
            ps.setString(9, nombre);

            int filas = ps.executeUpdate();
            if (filas > 0) {
                JOptionPane.showMessageDialog(null, "Producto actualizado.");
                cargarProductos();
            } else {
                JOptionPane.showMessageDialog(null, "No se encontró el producto para actualizar.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al actualizar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnActualizarProdActionPerformed

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        Dashboard dashboard = new Dashboard("A"); // o el permiso real que corresponda
        dashboard.setLocationRelativeTo(null);
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exitTxtMouseClicked

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        exitBtn.setBackground(Color.red);
        exitTxt.setForeground(Color.white);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        exitBtn.setBackground(Color.white);
        exitTxt.setForeground(Color.black);
    }//GEN-LAST:event_exitTxtMouseExited

    private void cmbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCategoriaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnActualizarProd;
    private javax.swing.JButton btnAgregarProductos;
    private javax.swing.JButton btnBuscarProd;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JComboBox<String> cmbIVA;
    private javax.swing.JComboBox<String> cmbMaterial;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JPanel exitBtn1;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JPanel header;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAlto1;
    private javax.swing.JLabel lblAncho;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCrearProd1;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblIVA;
    private javax.swing.JLabel lblListadoProd;
    private javax.swing.JLabel lblMaterial1;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JLabel lblStock;
    private javax.swing.JTable tblProductos;
    private javax.swing.JLabel title;
    private javax.swing.JTextField txtAlto;
    private javax.swing.JTextField txtAncho;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtProfundidad;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
