/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Main.BD;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Carlos Moyano
 */
public class Proveedores extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Proveedores.class.getName());

    /**
     * Creates new form Proveedores
     */
    public Proveedores() {
        initComponents();
        cargarProveedores();
        tablaProveedores.setDefaultEditor(Object.class, null);
        tablaProveedores.getSelectionModel().addListSelectionListener(evt -> {
          if (!evt.getValueIsAdjusting()) {
            llenarCamposDesdeTabla();
          }
        });
    }
    
    private void cargarProveedores() 
    {
        DefaultTableModel modelo = (DefaultTableModel) tablaProveedores.getModel();
        modelo.setRowCount(0);
        String sql = "SELECT prov_id, prov_nombre, prov_direccion, prov_telefono, prov_correo "
                   + "FROM MUE_PROVEEDORES "
                   + "ORDER BY prov_id";
        try (Connection cn = BD.conectar();
             PreparedStatement ps = cn.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) 
        {
            while (rs.next()) 
            {
                modelo.addRow(new Object[]{
                    rs.getInt("prov_id"),
                    rs.getString("prov_nombre"),
                    rs.getString("prov_direccion"),
                    rs.getString("prov_telefono"),
                    rs.getString("prov_correo")
                });
            }
        } catch (SQLException e) 
        {
            JOptionPane.showMessageDialog(this, "Error al cargar proveedores: " + e.getMessage());
        }
    }
    
    private void llenarCamposDesdeTabla() 
    {
        int fila = tablaProveedores.getSelectedRow();
        if (fila < 0) return;
        DefaultTableModel m = (DefaultTableModel) tablaProveedores.getModel();
        txtNombreProv.setText(m.getValueAt(fila, 1).toString());
        txtDireccionProv.setText(m.getValueAt(fila, 2).toString());
        txtTelefonoProv.setText(m.getValueAt(fila, 3).toString());
        txtCorreoProv.setText(m.getValueAt(fila, 4).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        lblMateriales = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel8 = new javax.swing.JPanel();
        txtDireccionProv = new javax.swing.JTextField();
        btnAgregarProv = new javax.swing.JButton();
        lblCrearProd5 = new javax.swing.JLabel();
        lblNombreCat3 = new javax.swing.JLabel();
        txtTelefonoProv = new javax.swing.JTextField();
        lblApellidoCli1 = new javax.swing.JLabel();
        txtNombreProv = new javax.swing.JTextField();
        lblApellidoCli2 = new javax.swing.JLabel();
        txtCorreoProv = new javax.swing.JTextField();
        lblApellidoCli3 = new javax.swing.JLabel();
        btnEliminarProv = new javax.swing.JButton();
        btnActualizarProv = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        lblListadoCat2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaProveedores = new javax.swing.JTable();
        exitBtn = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMateriales.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        lblMateriales.setText("Proveedores");
        jPanel7.add(lblMateriales, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel7.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 720, 20));

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDireccionProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionProvActionPerformed(evt);
            }
        });
        jPanel8.add(txtDireccionProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 230, -1));

        btnAgregarProv.setBackground(new java.awt.Color(255, 153, 0));
        btnAgregarProv.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnAgregarProv.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarProv.setText("AGREGAR");
        btnAgregarProv.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAgregarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProvActionPerformed(evt);
            }
        });
        jPanel8.add(btnAgregarProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 100, 30));

        lblCrearProd5.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblCrearProd5.setText("Agregar Proveedor:");
        jPanel8.add(lblCrearProd5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 200, -1));

        lblNombreCat3.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblNombreCat3.setText("Dirección:");
        jPanel8.add(lblNombreCat3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        txtTelefonoProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoProvActionPerformed(evt);
            }
        });
        jPanel8.add(txtTelefonoProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 230, -1));

        lblApellidoCli1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblApellidoCli1.setText("Telefono:");
        jPanel8.add(lblApellidoCli1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, -1));

        txtNombreProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProvActionPerformed(evt);
            }
        });
        jPanel8.add(txtNombreProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 230, -1));

        lblApellidoCli2.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblApellidoCli2.setText("Nombre");
        jPanel8.add(lblApellidoCli2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        txtCorreoProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoProvActionPerformed(evt);
            }
        });
        jPanel8.add(txtCorreoProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 230, -1));

        lblApellidoCli3.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblApellidoCli3.setText("Correo:");
        jPanel8.add(lblApellidoCli3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        btnEliminarProv.setBackground(new java.awt.Color(255, 153, 0));
        btnEliminarProv.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnEliminarProv.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarProv.setText("ELIMINAR");
        btnEliminarProv.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProvActionPerformed(evt);
            }
        });
        jPanel8.add(btnEliminarProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 100, 30));

        btnActualizarProv.setBackground(new java.awt.Color(255, 153, 0));
        btnActualizarProv.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnActualizarProv.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarProv.setText("ACTUALIZAR");
        btnActualizarProv.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnActualizarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarProvActionPerformed(evt);
            }
        });
        jPanel8.add(btnActualizarProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 100, 30));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 720, 170));

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblListadoCat2.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblListadoCat2.setText("Listado de Proveedores");
        jPanel9.add(lblListadoCat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 200, -1));

        tablaProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id del Proveedor", "Nombre", "Dirección", "Teléfono", "Correo"
            }
        ));
        jScrollPane3.setViewportView(tablaProveedores);

        jPanel9.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 680, 190));

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 720, 270));

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));

        exitTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("<");
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel7.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDireccionProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionProvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionProvActionPerformed

    private void btnAgregarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProvActionPerformed

        String nombre = txtNombreProv.getText().trim();
        String direccion = txtDireccionProv.getText().trim();
        String telefono = txtTelefonoProv.getText().trim();
        String correo = txtCorreoProv.getText().trim();

        if(nombre.isEmpty() || direccion.isEmpty() || telefono.isEmpty() || correo.isEmpty()) 
        {
            JOptionPane.showMessageDialog(this, "Campos incompletos");
            return;
        }

        String sql = "INSERT INTO MUE_PROVEEDORES(prov_id, prov_nombre, prov_direccion, prov_telefono, prov_correo) "
                   + "VALUES(prov_id_seq.NEXTVAL, ?, ?, ?, ?)";
        try (Connection cn = BD.conectar();
             PreparedStatement ps = cn.prepareStatement(sql)) 
        {
            ps.setString(1, nombre);
            ps.setString(2, direccion);
            ps.setString(3, telefono);
            ps.setString(4, correo);
            ps.executeUpdate();

            JOptionPane.showMessageDialog(this, "Proveedor agregado correctamente.");

            txtNombreProv.setText("");
            txtDireccionProv.setText("");
            txtTelefonoProv.setText("");
            txtCorreoProv.setText("");
            
            cargarProveedores();
        } 
        catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(this, "Error al agregar proveedor: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnAgregarProvActionPerformed

    private void txtTelefonoProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoProvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoProvActionPerformed

    private void txtNombreProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProvActionPerformed

    private void txtCorreoProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoProvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoProvActionPerformed

    private void btnEliminarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProvActionPerformed
        // 1) Asegurarse de que haya una fila seleccionada
        int fila = tablaProveedores.getSelectedRow();
        
        if (fila < 0) 
        {
            JOptionPane.showMessageDialog(this, "Seleccione un proveedor para eliminar.");
            return;
        }
        
        DefaultTableModel modelo = (DefaultTableModel) tablaProveedores.getModel();
        int provId = (int) modelo.getValueAt(fila, 0);

        int resp = JOptionPane.showConfirmDialog(
            this,
            "¿Está seguro de eliminar al proveedor con ID " + provId + "?",
            "Confirmar eliminación",
            JOptionPane.YES_NO_OPTION
        );
        
        if (resp != JOptionPane.YES_OPTION)
        {
            return;
        }

        String sql = "DELETE FROM MUE_PROVEEDORES WHERE prov_id = ?";
        try (Connection cn = BD.conectar();
             PreparedStatement ps = cn.prepareStatement(sql)) 
        {
            ps.setInt(1, provId);
            int afectados = ps.executeUpdate();

            if (afectados > 0) 
            {
                JOptionPane.showMessageDialog(this, "Proveedor eliminado correctamente.");
                
                txtNombreProv.setText("");
                txtDireccionProv.setText("");
                txtTelefonoProv.setText("");
                txtCorreoProv.setText("");
                
                cargarProveedores();
            }
            else 
            {
                JOptionPane.showMessageDialog(this, "No se encontró el proveedor.");
            }
        }
        catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(this, "Error al eliminar proveedor: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnEliminarProvActionPerformed

    private void btnActualizarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarProvActionPerformed
        
        int fila = tablaProveedores.getSelectedRow();
        if (fila < 0) 
        {
            JOptionPane.showMessageDialog(this, "Seleccione un proveedor para actualizar.");
            return;
        }

        DefaultTableModel modelo = (DefaultTableModel) tablaProveedores.getModel();
        int provId = (int) modelo.getValueAt(fila, 0);

        String nombre    = txtNombreProv.getText().trim();
        String direccion = txtDireccionProv.getText().trim();
        String telefono  = txtTelefonoProv.getText().trim();
        String correo    = txtCorreoProv.getText().trim();

        if (nombre.isEmpty() || direccion.isEmpty() || telefono.isEmpty() || correo.isEmpty()) 
        {
            JOptionPane.showMessageDialog(this, "Campos incompletos");
            return;
        }

        String sql = ""
            + "UPDATE MUE_PROVEEDORES "
            + "   SET prov_nombre    = ?, "
            + "       prov_direccion = ?, "
            + "       prov_telefono  = ?, "
            + "       prov_correo    = ? "
            + " WHERE prov_id        = ?";

        try (Connection cn = BD.conectar();
             PreparedStatement ps = cn.prepareStatement(sql)) 
        {
            ps.setString(1, nombre);
            ps.setString(2, direccion);
            ps.setString(3, telefono);
            ps.setString(4, correo);
            ps.setInt   (5, provId);

            int filas = ps.executeUpdate();
            if (filas > 0) 
            {
                JOptionPane.showMessageDialog(this, "Proveedor actualizado correctamente.");
                
                txtNombreProv.setText("");
                txtDireccionProv.setText("");
                txtTelefonoProv.setText("");
                txtCorreoProv.setText("");
                
                cargarProveedores(); 
            }
            else 
            {
                JOptionPane.showMessageDialog(this, "No se encontró el proveedor.");
            }
        } 
        catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(this, "Error al actualizar proveedor: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnActualizarProvActionPerformed

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        Dashboard dashboard = new Dashboard("A"); // o el permiso real que corresponda
        dashboard.setLocationRelativeTo(null);
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exitTxtMouseClicked

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        exitBtn.setBackground(Color.red);
        exitTxt.setForeground(Color.white);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        exitBtn.setBackground(Color.white);
        exitTxt.setForeground(Color.black);
    }//GEN-LAST:event_exitTxtMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarProv;
    private javax.swing.JButton btnAgregarProv;
    private javax.swing.JButton btnEliminarProv;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblApellidoCli1;
    private javax.swing.JLabel lblApellidoCli2;
    private javax.swing.JLabel lblApellidoCli3;
    private javax.swing.JLabel lblCrearProd5;
    private javax.swing.JLabel lblListadoCat2;
    private javax.swing.JLabel lblMateriales;
    private javax.swing.JLabel lblNombreCat3;
    private javax.swing.JTable tablaProveedores;
    private javax.swing.JTextField txtCorreoProv;
    private javax.swing.JTextField txtDireccionProv;
    private javax.swing.JTextField txtNombreProv;
    private javax.swing.JTextField txtTelefonoProv;
    // End of variables declaration//GEN-END:variables
}
